// Real Chromium + isolated local database, never the existing application schema.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict'),{spawn,spawnSync}=require('child_process');
require('dotenv').config({path:path.join(__dirname,'../.env')});const {PrismaClient}=require('@prisma/client'),bcrypt=require('bcryptjs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
async function main(){
 const url=new URL(process.env.DATABASE_URL);assert.ok(['localhost','127.0.0.1'].includes(url.hostname)&&url.pathname==='/smartlab_test','Local test database required');assert.ok(process.env.SMARTLAB_EVIDENCE_DIR,'Evidence directory required');const out=process.env.SMARTLAB_EVIDENCE_DIR;fs.mkdirSync(out,{recursive:true});
 const schema='smartlab_ribbon_'+Date.now()+'_'+crypto.randomBytes(4).toString('hex');assert.match(schema,/^smartlab_ribbon_\d+_[a-f0-9]{8}$/);const owner=new PrismaClient();url.searchParams.set('schema',schema);const env={...process.env,DATABASE_URL:url.toString(),PORT:'3123',NODE_ENV:'production',FRONTEND_URL:'http://localhost:3123',JWT_SECRET:crypto.randomBytes(32).toString('hex'),SMTP_PASS:''};const backend=path.resolve(__dirname,'..');let db,server,browser;const results=[],errors=[];
 try{
 const m=spawnSync(process.execPath,[require.resolve('prisma/build/index.js'),'migrate','deploy'],{cwd:backend,env,stdio:'ignore',windowsHide:true,timeout:60000});assert.equal(m.status,0,'Migrations');db=new PrismaClient({datasources:{db:{url:url.toString()}}});
 const year=await db.academicYear.create({data:{year:'2026-2027',isActive:true}}),term=await db.term.create({data:{name:'First semester',isActive:true}});const password=crypto.randomBytes(16).toString('hex'),passwordHash=await bcrypt.hash(password,10),users={};for(const role of ['ADMIN','FACULTY','STUDENT'])users[role]=await db.user.create({data:{email:role.toLowerCase()+'@ribbon.invalid',firstName:role,lastName:'Review',passwordHash,role}});
 const faculty=await db.facultyProfile.create({data:{userId:users.FACULTY.id}});await db.studentProfile.create({data:{userId:users.STUDENT.id}});const room=await db.room.create({data:{name:'Computer laboratory',roomNumber:'101',isComputerLab:true}});await db.equipment.createMany({data:Array.from({length:35},(_,i)=>({name:'Ribbon equipment '+i,totalQuantity:5,availableQuantity:5}))});await db.labSchedule.createMany({data:Array.from({length:35},(_,i)=>({roomId:room.id,facultyId:faculty.id,academicYearId:year.id,termId:term.id,createdBy:users.ADMIN.id,dayOfWeek:i%7,scheduleType:'WEEKLY',timeStart:new Date('2026-10-01T01:00:00Z'),timeEnd:new Date('2026-10-01T02:00:00Z')}))});
 server=spawn(process.execPath,['dist/server.js'],{cwd:backend,env,stdio:'ignore',windowsHide:true});for(let i=0;i<600;i++){try{if((await fetch('http://localhost:3123/ready')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}assert.equal((await fetch('http://localhost:3123/ready')).status,200);
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const surfaces=[['requests','/admin/requests','ADMIN'],['equipment','/admin/equipment','ADMIN'],['schedule','/admin/schedule','ADMIN'],['accounts','/admin/users','ADMIN'],['directory','/admin/academic-directory','ADMIN'],['audit','/admin/audit-logs','ADMIN'],['reports','/admin/reports','ADMIN'],['reports-requests','/admin/reports','ADMIN'],['reports-schedules','/admin/reports','ADMIN'],['reports-equipment','/admin/reports','ADMIN'],['directory-rooms','/admin/academic-directory','ADMIN'],['faculty','/faculty/panel','FACULTY'],['student','/student/panel','STUDENT']];
 const selected=process.env.RIBBON_SURFACES?surfaces.filter(s=>process.env.RIBBON_SURFACES.split(',').includes(s[0])):surfaces;
 for(const [name,route,role] of selected){const login=await fetch('http://localhost:3123/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:users[role].email,password})});assert.equal(login.status,200);const auth=await login.json();const context=await browser.newContext({viewport:{width:1280,height:1000}});await context.addInitScript(({user,token})=>{localStorage.setItem('token',token);localStorage.setItem('auth-storage',JSON.stringify({state:{user,token,isAuthenticated:true},version:0}))},auth);const page=await context.newPage();page.on('pageerror',e=>errors.push({name,type:'runtime',message:e.message}));page.on('console',m=>{if(m.type()==='error')errors.push({name,type:'console',message:m.text()})});page.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400)errors.push({name,type:'http',status:r.status(),url:new URL(r.url()).pathname})});await page.goto('http://localhost:3123'+route);if(role!=='ADMIN')await page.getByText('View Schedules',{exact:true}).click();await page.locator('.page-control-ribbon').first().waitFor();await page.waitForLoadState('networkidle');if(name.startsWith('reports-')){await page.getByTestId({'reports-requests':'tab-requests','reports-schedules':'tab-schedule','reports-equipment':'tab-equipment'}[name]).click();await page.waitForLoadState('networkidle');}if(name==='directory-rooms'){await page.getByRole('tab',{name:/Rooms/}).click();await page.waitForLoadState('networkidle');}
 for(const width of [1280,1024,390]){console.log('CHECK',name,width);await page.setViewportSize({width,height:1000});await page.waitForTimeout(600);const ribbon=page.locator('.page-control-ribbon').first();const toggle=ribbon.getByRole('button',{name:'Hide controls',exact:true});if(!await toggle.count())await ribbon.getByRole('button',{name:'Show controls',exact:true}).click();const row={surface:name,width,issues:[]};
 const scan=async()=>page.evaluate(()=>{const r=document.querySelector('.page-control-ribbon');return [...r.querySelectorAll('button,input,select,textarea,a')].filter(e=>{const s=getComputedStyle(e);return !e.closest('[hidden]')&&s.visibility!=='hidden'&&s.display!=='none'&&e.getClientRects().length&&!e.matches('.sr-only,[aria-hidden="true"]')}).flatMap(e=>{const b=(e.matches('input[type=checkbox],input[type=radio]')&&e.labels?.length?e.labels[0]:e).getBoundingClientRect(),a=e.getAttribute('aria-label')||e.textContent?.trim()||e.getAttribute('placeholder')||e.tagName;const problems=[];if(b.height<39.5||b.width<39.5)problems.push({kind:'target',label:a,height:b.height,width:b.width});if(b.left<-.5||b.right>innerWidth+.5)problems.push({kind:'overflow',label:a,left:b.left,right:b.right});if(e.hasAttribute('aria-controls')&&!document.getElementById(e.getAttribute('aria-controls')))problems.push({kind:'aria-controls',label:a});if(e.matches('input:not([type="hidden"]),textarea')&&!e.labels?.length&&!e.getAttribute('aria-label')&&!e.getAttribute('aria-labelledby'))problems.push({kind:'label',label:a});return problems})});row.issues.push(...await scan());
 const advanced=ribbon.locator('.ribbon-bottom-control');if(await advanced.count()){assert.equal(await advanced.count(),1,'one handle');await advanced.click();row.issues.push(...await scan());await advanced.click();row.portalHandle=true;}
 const search=ribbon.locator('input[type="search"], input[placeholder*="Search"]').first();if(await search.count()){await search.fill('Ribbon');await page.waitForTimeout(350);row.issues.push(...await scan());row.activeSearch=true;}
 const actionsBefore=await ribbon.locator('.page-control-ribbon__bar button').allTextContents();
 const dropdown=ribbon.locator('button[aria-haspopup="listbox"]:visible').first();if(await dropdown.count()){await dropdown.focus();await page.keyboard.press('ArrowDown');assert.equal(await dropdown.getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await dropdown.getAttribute('aria-expanded'),'false');row.dropdownKeyboard=true;}
 const contentId=await toggle.getAttribute('aria-controls');const before=await ribbon.locator('input').evaluateAll(es=>es.map(e=>e.value));const summary=await ribbon.locator('.page-control-ribbon__summary').innerText();assert.ok(summary.trim());await toggle.focus();await page.keyboard.press('Enter');assert.equal(await page.locator('[id="'+contentId+'"]').isVisible(),false);assert.equal(await page.evaluate(()=>document.activeElement?.textContent?.includes('Show controls')),true);assert.equal(await ribbon.locator('.ribbon-bottom-control').count(),0);assert.ok(await ribbon.locator('.page-control-ribbon__bar').isVisible());const actionsAfter=await ribbon.locator('.page-control-ribbon__bar button').allTextContents();assert.equal(actionsAfter.length,actionsBefore.length);const normalizeActions=a=>a.slice(0,-1).map(s=>s.replace('Refreshing…','Refresh'));assert.deepEqual(normalizeActions(actionsAfter),normalizeActions(actionsBefore));row.visibleActions=true;assert.notEqual(await ribbon.getByRole('button',{name:'Show controls',exact:true}).evaluate(e=>getComputedStyle(e).outlineStyle),'none');await page.keyboard.press('Space');assert.equal(await toggle.getAttribute('aria-expanded'),'true');assert.deepEqual(await ribbon.locator('input').evaluateAll(es=>es.map(e=>e.value)),before);row.collapseKeyboardState=true;
 if(await search.count()){await search.fill('');await page.waitForTimeout(350);}
 await page.screenshot({path:path.join(out,'SmartLab-Fix-16-'+name+'-'+width+'.png'),fullPage:true});
 row.sticky=await page.evaluate(()=>{const r=document.querySelector('.page-control-ribbon');const shell=r.closest('.filter-toolbar--sticky')||r;return getComputedStyle(shell).position});if(row.sticky!=='sticky')row.issues.push({kind:'sticky',position:row.sticky});
 row.scroll=await page.evaluate(async()=>{const scroll=document.querySelector('.portal-content'),r=document.querySelector('.page-control-ribbon'),shell=r.closest('.filter-toolbar--sticky')||r;scroll.scrollTop=150;await new Promise(requestAnimationFrame);const moved=scroll.scrollTop;const delta=shell.getBoundingClientRect().top-scroll.getBoundingClientRect().top;scroll.scrollTop=0;return {moved,delta}});if(row.scroll.moved>100 && Math.abs(row.scroll.delta)>2)row.issues.push({kind:'sticky-scroll',...row.scroll});
 await page.emulateMedia({media:'print'});row.print=await page.evaluate(()=>{const r=document.querySelector('.page-control-ribbon');const shell=r.closest('.filter-toolbar--sticky')||r;return {position:getComputedStyle(shell).position,handles:[...r.querySelectorAll('.ribbon-bottom-control')].every(e=>getComputedStyle(e).display==='none')}});if(row.print.position!=='static'||!row.print.handles)row.issues.push({kind:'print',...row.print});await page.emulateMedia({media:'screen'});await page.waitForTimeout(600);results.push(row);console.log(name,width,row.issues.length?'ISSUES '+JSON.stringify(row.issues):'PASS');}
 await context.close();}
 }finally{if(browser)await browser.close();if(server&&server.exitCode===null){server.kill();await Promise.race([new Promise(r=>server.once('exit',r)),new Promise(r=>setTimeout(r,5000))])}if(db)await db.$disconnect();await owner.$executeRawUnsafe('DROP SCHEMA IF EXISTS "'+schema+'" CASCADE');await owner.$disconnect();fs.writeFileSync(path.join(out,'SmartLab-Fix-16-Browser-Matrix.json'),JSON.stringify({results,errors},null,2));}
 assert.equal(errors.length,0,'Browser errors');assert.equal(results.length,process.env.RIBBON_SURFACES?process.env.RIBBON_SURFACES.split(',').length*3:39);assert.equal(results.flatMap(r=>r.issues).length,0,'Ribbon findings remain');
}
main().catch(e=>{console.error(e.stack);process.exitCode=1});



