const express=require('express'),path=require('path'),fs=require('fs');require('dotenv').config({path:path.join(__dirname,'../.env')});const mockClients=[],mockQueries=[];
jest.mock('@prisma/client',()=>{const real=jest.requireActual('@prisma/client');return {...real,PrismaClient:jest.fn(()=>{const c=new real.PrismaClient({log:[{emit:'event',level:'query'}]});c.$on('query',e=>mockQueries.push({query:e.query,duration:e.duration}));mockClients.push(c);return c})}});
const {PrismaClient}=require('@prisma/client'),{generateToken}=require('../dist/middleware/auth'),{errorResponseContract,errorHandler}=require('../dist/middleware/errors');
let db,server,base,admin,token,year,term,profile,room;const tag='paging-'+Date.now(),size=251,equipmentIds=[],requestIds=[],scheduleIds=[],userIds=[];const evidence=[];
beforeAll(async()=>{const u=new URL(process.env.DATABASE_URL);if(!['localhost','127.0.0.1'].includes(u.hostname)||u.pathname!='/smartlab_test')throw Error('Local test DB required');db=new PrismaClient();admin=await db.user.create({data:{email:tag+'admin@test',firstName:tag,lastName:'Admin',role:'ADMIN',passwordHash:'unused'}});token=generateToken(admin);year=await db.academicYear.create({data:{year:tag}});term=await db.term.create({data:{name:tag}});profile=await db.facultyProfile.create({data:{userId:admin.id}});room=await db.room.create({data:{name:tag}});
await db.equipment.createMany({data:Array.from({length:size},(_,i)=>({id:tag+'e'+String(i).padStart(4,'0'),name:tag,totalQuantity:2,availableQuantity:2}))});equipmentIds.push(...Array.from({length:size},(_,i)=>tag+'e'+String(i).padStart(4,'0')));
await db.user.createMany({data:Array.from({length:size},(_,i)=>({id:tag+'u'+i,email:tag+i+'@test',firstName:tag,lastName:'Student',role:'STUDENT',passwordHash:'PRIVATE HASH'}))});userIds.push(...Array.from({length:size},(_,i)=>tag+'u'+i));
await db.borrowRequest.createMany({data:Array.from({length:size},(_,i)=>({id:tag+'r'+i,requestedBy:admin.id,purpose:tag,academicYearId:year.id,termId:term.id,dateNeeded:new Date('2041-06-12'),status:i%2?'PENDING':'APPROVED'}))});requestIds.push(...Array.from({length:size},(_,i)=>tag+'r'+i));
await db.labSchedule.createMany({data:Array.from({length:size},(_,i)=>({id:tag+'s'+i,roomId:room.id,facultyId:profile.id,academicYearId:year.id,termId:term.id,createdBy:admin.id,dayOfWeek:1,timeStart:new Date('2041-06-12T00:00:00Z'),timeEnd:new Date('2041-06-12T01:00:00Z')}))});scheduleIds.push(...Array.from({length:size},(_,i)=>tag+'s'+i));
const app=express();app.use(errorResponseContract);app.use(express.json());for(const n of ['equipment','users','borrowRequests','labSchedules'])app.use('/'+n,require('../dist/routes/'+n).default);app.use(errorHandler);server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s))});base='http://127.0.0.1:'+server.address().port});
afterAll(async()=>{if(server)await new Promise(r=>server.close(r));if(db&&admin){await db.labSchedule.deleteMany({where:{id:{in:scheduleIds}}});await db.borrowRequest.deleteMany({where:{id:{in:requestIds}}});await db.equipment.deleteMany({where:{id:{in:equipmentIds}}});await db.user.deleteMany({where:{id:{in:[admin.id,...userIds]}}});if(room)await db.room.delete({where:{id:room.id}});if(year)await db.academicYear.delete({where:{id:year.id}});if(term)await db.term.delete({where:{id:term.id}})}await Promise.all(mockClients.map(c=>c.$disconnect()));fs.writeFileSync(path.join(process.env.SMARTLAB_EVIDENCE_DIR||__dirname,'SmartLab-Fix-14-Measurements.json'),JSON.stringify(evidence,null,2))});
async function get(url){const start=performance.now();mockQueries.length=0;const r=await fetch(base+url,{headers:{Authorization:'Bearer '+token}});const text=await r.text();return {status:r.status,data:JSON.parse(text),total:Number(r.headers.get('x-total-count')),bytes:Buffer.byteLength(text),ms:performance.now()-start,queries:[...mockQueries]}}
function query(name){return name==='equipment'?'search='+tag:name==='users'?'search='+tag+'&role=STUDENT':'academicYearId='+year.id+'&termId='+term.id}
function rows(r,name){return name==='borrowRequests'?r.data.requests:name==='labSchedules'?r.data.schedules:r.data}
for(const name of ['equipment','users','borrowRequests','labSchedules']){
test(name+' defaults to 25 and preserves exact total',async()=>{const r=await get('/'+name+'?'+query(name));expect(r.status).toBe(200);expect(rows(r,name)).toHaveLength(25);expect(r.total).toBe(size);evidence.push({endpoint:name,fixtures:size,pageSize:25,responseBytes:r.bytes,elapsedMs:r.ms,queryCount:r.queries.length,databaseMs:r.queries.reduce((n,q)=>n+q.duration,0),nodeRssBytes:process.memoryUsage().rss});if(name==='users'){expect(JSON.stringify(r.data)).not.toContain('PRIVATE HASH');expect(r.queries.filter(q=>q.query.includes('users')).every(q=>!q.query.includes('passwordHash'))).toBe(true)}});
test(name+' stable tied order, complete pages without duplicates, empty tail',async()=>{const all=[];for(let page=1;page<=3;page++){const r=await get('/'+name+'?'+query(name)+'&page='+page+'&pageSize=100');expect(r.status).toBe(200);all.push(...rows(r,name).map(x=>x.id??x.user_id));}expect(all).toHaveLength(size);expect(new Set(all).size).toBe(size);const a=await get('/'+name+'?'+query(name)+'&page=2&pageSize=100'),b=await get('/'+name+'?'+query(name)+'&page=2&pageSize=100');expect(rows(a,name)).toEqual(rows(b,name));expect(rows(await get('/'+name+'?'+query(name)+'&page=100'),name)).toHaveLength(0)});
test.each(['page=0','page=-1','page=1.5','page=10001','pageSize=101','pageSize=0','pageSize=all'])(name+' rejects %s',async invalid=>expect((await get('/'+name+'?'+query(name)+'&'+invalid)).status).toBe(400));
}
test('request counts grouped once and filtered total matches selected status',async()=>{const r=await get('/borrowRequests?'+query('borrowRequests')+'&status=PENDING');expect(r.total).toBe(125);expect(r.data.allTotal).toBe(size);expect(r.data.stats.APPROVED).toBe(126);expect(r.queries.filter(q=>q.query.includes('GROUP BY')).length).toBe(1)});
test('personal request pagination shares filters and exact total',async()=>{const r=await get('/borrowRequests/my-requests?'+query('borrowRequests')+'&status=PENDING&page=2&pageSize=20');expect(r.status).toBe(200);expect(r.data.requests).toHaveLength(20);expect(r.total).toBe(125);expect(r.data.requests.every(row=>row.status==='PENDING')).toBe(true)});
test('schedule source and text filters execute before paging and totals',async()=>{const r=await get('/labSchedules?'+query('labSchedules')+'&search='+tag+'&source=admin&pageSize=10');expect(r.status).toBe(200);expect(r.data.schedules).toHaveLength(10);expect(r.total).toBe(size);const empty=await get('/labSchedules?'+query('labSchedules')+'&source=request');expect(empty.total).toBe(0);expect(empty.data.schedules).toHaveLength(0)});
