const path=require('path'),express=require('express');require('dotenv').config({path:path.join(__dirname,'../.env')});const mockClients=[];
jest.mock('@prisma/client',()=>{const real=jest.requireActual('@prisma/client');return {...real,PrismaClient:jest.fn((...a)=>{const c=new real.PrismaClient(...a);mockClients.push(c);return c})}});
const {PrismaClient}=require('@prisma/client'),{generateToken}=require('../dist/middleware/auth'),{errorResponseContract,errorHandler}=require('../dist/middleware/errors');
const names=['auth','equipment','users','borrowRequests','labSchedules','academicDirectory','conflicts','equipmentConflicts','equipmentAdjustments','notifications','reports','academicPeriod','auditLogs'];
const routers=Object.fromEntries(names.map(n=>[n,require('../dist/routes/'+n).default]));const endpoints=names.flatMap(n=>routers[n].stack.filter(l=>l.route).flatMap(l=>Object.keys(l.route.methods).map(m=>[n,m,l.route.path]))).filter(([n,,p])=>!(n==='auth'&&['/login','/reactivation','/forgot-password','/reset-password'].includes(p)));
let db,server,base,admin,faculty,other,student,profile,otherProfile,year,term,room,stock,own,assigned,foreign,schedule,notice;const users=[],tag='privacy-'+Date.now();
beforeAll(async()=>{const u=new URL(process.env.DATABASE_URL);if(!['localhost','127.0.0.1'].includes(u.hostname)||u.pathname!='/smartlab_test')throw Error('Local smartlab_test required');db=new PrismaClient();async function user(role,label){const v=await db.user.create({data:{email:tag+label+'@test.local',firstName:label,lastName:'Private',role,passwordHash:'unused'}});users.push(v.id);v.token=generateToken(v);return v}
admin=await user('ADMIN','admin');faculty=await user('FACULTY','faculty');other=await user('FACULTY','other');student=await user('STUDENT','student');profile=await db.facultyProfile.create({data:{userId:faculty.id}});otherProfile=await db.facultyProfile.create({data:{userId:other.id}});year=await db.academicYear.findFirst({where:{isActive:true}});term=await db.term.findFirst({where:{isActive:true}});if(!year||!term)throw Error('Existing active local test period required');room=await db.room.create({data:{name:tag,roomNumber:tag}});stock=await db.equipment.create({data:{name:tag,totalQuantity:3,availableQuantity:3}});
async function request(requestedBy,facultyId){return db.borrowRequest.create({data:{requestType:'LABORATORY',requestedBy,facultyId,academicYearId:year.id,termId:term.id,roomId:room.id,dateNeeded:new Date('2040-06-12T00:00:00+08:00'),timeStart:new Date('2040-06-12T08:00:00+08:00'),timeEnd:new Date('2040-06-12T09:00:00+08:00'),purpose:'PRIVATE PURPOSE',contactDetails:'PRIVATE CONTACT',notes:'PRIVATE NOTES',items:{create:{equipmentId:stock.id,quantity:1}}}})}
own=await request(faculty.id,null);assigned=await request(student.id,profile.id);foreign=await request(other.id,otherProfile.id);schedule=await db.labSchedule.create({data:{facultyId:otherProfile.id,roomId:room.id,academicYearId:year.id,termId:term.id,scheduleType:'ONE_TIME',scheduleDate:foreign.dateNeeded,dayOfWeek:2,timeStart:foreign.timeStart,timeEnd:foreign.timeEnd,borrowRequestId:foreign.id,createdBy:admin.id}});notice=await db.notification.create({data:{userId:other.id,type:'SYSTEM_ANNOUNCEMENT',title:'Equipment Request Adjusted',message:'PRIVATE',borrowRequestId:foreign.id,referenceType:'borrow_request',referenceId:foreign.id}});
const app=express();app.use(errorResponseContract);app.use(express.json());for(const n of names)app.use('/'+n,routers[n]);app.use(errorHandler);app.use((_req,res)=>res.status(404).json({error:'Not found'}));server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s))});base='http://127.0.0.1:'+server.address().port});
afterAll(async()=>{if(server)await new Promise(r=>server.close(r));if(db&&admin){await db.notification.deleteMany({where:{userId:{in:users}}});await db.auditLog.deleteMany({where:{actorUserId:{in:users}}});await db.labSchedule.deleteMany({where:{createdBy:admin.id}});await db.borrowRequest.deleteMany({where:{requestedBy:{in:users}}});if(stock)await db.equipment.delete({where:{id:stock.id}});if(room)await db.room.delete({where:{id:room.id}});await db.user.deleteMany({where:{id:{in:users}}});}await Promise.all(mockClients.map(c=>c.$disconnect()))});
async function api(method,url,actor,body){const r=await fetch(base+url,{method:method.toUpperCase(),headers:{'Content-Type':'application/json',...(actor?{Authorization:'Bearer '+actor.token}:{})},body:method==='get'?undefined:JSON.stringify(body??{})});return {status:r.status,data:await r.json()}}const period=()=>'?academicYearId='+year.id+'&termId='+term.id;
test.each(endpoints)('%s %s %s requires authentication',async(n,m,p)=>expect((await api(m,'/'+n+p.replace(/:[^/]+/g,'missing'))).status).toBe(401));
test.each([['users','post','/'],['equipment','post','/'],['borrowRequests','patch','/missing/approve'],['labSchedules','post','/admin/create'],['academicDirectory','get','/'],['equipmentAdjustments','post','/adjust-equipment'],['reports','get','/equipment.pdf'],['academicPeriod','get','/'],['auditLogs','get','/']])('%s privileged route rejects faculty/student',async(n,m,p)=>{for(const a of [student,faculty])expect((await api(m,'/'+n+p,a)).status).toBe(403)});
test('faculty list and counts enforce scope',async()=>{const r=await api('get','/borrowRequests'+period(),faculty);expect(r.status).toBe(200);expect(r.data.requests.map(x=>x.id).sort()).toEqual([own.id,assigned.id].sort());expect(r.data.total).toBe(2);expect(r.data.stats.PENDING).toBe(2)});
test('faculty detail permits own and assigned, excludes unrelated',async()=>{for(const r of [own,assigned])expect((await api('get','/borrowRequests/'+r.id+period(),faculty)).status).toBe(200);expect((await api('get','/borrowRequests/'+foreign.id+period(),faculty)).status).toBe(404)});
test('student detail and list protected; admin retains access',async()=>{expect((await api('get','/borrowRequests'+period(),student)).status).toBe(403);expect((await api('get','/borrowRequests/'+foreign.id+period(),student)).status).toBe(404);expect((await api('get','/borrowRequests/'+foreign.id+period(),admin)).status).toBe(200)});
test('faculty equipment history is scoped',async()=>{const r=await api('get','/equipment/'+stock.id,faculty);expect(r.status).toBe(200);expect(r.data.requestItems.map(i=>i.borrowRequest.id).sort()).toEqual([own.id,assigned.id].sort())});
test('shared schedules omit linked private request',async()=>{for(const a of [student,faculty]){const r=await api('get','/labSchedules/'+schedule.id+period(),a);expect(r.status).toBe(200);expect(r.data.schedule.borrowRequest).toBeUndefined();expect(r.data.schedule.borrowRequestId).toBeUndefined();expect(r.data.schedule.createdBy).toBeUndefined();expect(JSON.stringify(r.data)).not.toContain('PRIVATE');expect((await api('get','/labSchedules'+period()+'&roomId='+room.id,a)).data.schedules[0].borrowRequestId).toBeUndefined()}});
const input=()=>({academicYearId:year.id,termId:term.id,date:'2040-06-12',timeStart:'08:00',timeEnd:'09:00',equipment:[{equipmentId:stock.id,requestedQuantity:1}]});const roomInput=()=>({roomId:room.id,academicYearId:year.id,termId:term.id,scheduleType:'ONE_TIME',scheduleDate:'2040-06-12',timeStart:foreign.timeStart.toISOString(),timeEnd:foreign.timeEnd.toISOString()});
function privateFree(r){expect(r.status).toBe(200);for(const v of ['PRIVATE','@test.local',foreign.id,other.id,'other Private'])expect(JSON.stringify(r.data)).not.toContain(v)}
test('equipment previews anonymize request details',async()=>{for(const a of [student,faculty]){privateFree(await api('post','/equipmentConflicts/conflicts',a,input()));privateFree(await api('get','/equipmentConflicts/availability?'+new URLSearchParams({...input(),equipment:''}),a))}});
test('room conflicts anonymize request details',async()=>{const r=await api('post','/conflicts/check',student,roomInput());privateFree(r);expect(r.data.hasConflicts).toBe(true)});
test('foreign exclusions rejected',async()=>{expect((await api('post','/equipmentConflicts/conflicts',student,{...input(),excludeRequestId:foreign.id})).status).toBe(403);expect((await api('post','/conflicts/check',student,{...roomInput(),excludeScheduleId:schedule.id})).status).toBe(403)});
test('cross-user notifications, profiles, adjustments, request mutations denied',async()=>{for(const [m,url,b] of [['patch','/notifications/'+notice.id+'/read',{}],['post','/equipmentAdjustments/'+notice.id+'/respond',{action:'cancel'}],['get','/users/'+other.id,{}],['put','/borrowRequests/'+foreign.id,{}],['patch','/borrowRequests/'+foreign.id+'/cancel',{}]])expect((await api(m,url,student,b)).status).toBe(403);expect((await db.notification.findUnique({where:{id:notice.id}})).isRead).toBe(false);expect((await db.borrowRequest.findUnique({where:{id:foreign.id}})).status).toBe('PENDING')});
test('public registration disabled',async()=>expect((await api('post','/auth/register',null,{role:'ADMIN'})).status).toBe(404));

test.each(['/reactivation','/forgot-password','/reset-password'])('public recovery %s validates its payload',async p=>expect((await api('post','/auth'+p,null,{})).status).toBe(400));
