import { useState } from 'react';
import { studentAcademicApi } from '../../services/api';
import ConfirmationModal from '../shared/ConfirmationModal';
type Row = {studentId:string;name:string;email:string;blocked:string|null;fingerprint:string;programId:string;yearLevel:number|null;status:string;sourceYearLevel:number|null;requiresGraduationReview:boolean;selected:boolean;archiveAccount:boolean};
type Props = {yearId:string;years:{id:string;year:string}[];studentIds:string[];programs:{id:string;code:string;name:string}[];onSaved:()=>void};
const control='mt-1.5 min-h-11 w-full rounded-xl border border-[#dcc8c2] bg-white px-3 text-sm text-[#321d1d] outline-none transition focus:border-[#800000] focus:ring-2 focus:ring-[#800000]/10';
export default function StudentAcademicBatch({yearId,years,studentIds,programs,onSaved}:Props) {
 const [mode,setMode]=useState('SETUP'),[sourceYearId,setSource]=useState(''),[rows,setRows]=useState<Row[]|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[error,setError]=useState('');
 const selected=rows?.filter(row=>row.selected&&!row.blocked)??[];
 const target=years.find(year=>year.id===yearId)?.year;
 const fail=(e:unknown)=>setError((e as {response?:{data?:{error?:string}}})?.response?.data?.error??'Unable to process batch. Reload and try again.');
 const preview=async()=>{setBusy(true);setError('');setRows(null);try{const response=await studentAcademicApi.previewBatch({mode,academicYearId:yearId,sourceYearId,studentIds});setRows(response.data.rows.map((row:Row)=>({...row,selected:!row.blocked&&!row.requiresGraduationReview,archiveAccount:false})));}catch(e){fail(e);}finally{setBusy(false);}};
 const save=async()=>{setBusy(true);setError('');try{await studentAcademicApi.commitBatch({mode,academicYearId:yearId,sourceYearId,reason,rows:selected.map(({studentId,fingerprint,programId,yearLevel,status,archiveAccount})=>({studentId,fingerprint,programId,yearLevel,status,archiveAccount}))});setConfirm(false);setRows(null);onSaved();}catch(e){setConfirm(false);fail(e);}finally{setBusy(false);}};
 const change=(id:string,patch:Partial<Row>)=>setRows(current=>current?.map(row=>row.studentId===id?{...row,...patch}:row)??null);
 return <section aria-label="Bulk academic records" className="mt-5 border-t-2 border-[#c8aaa2] pt-5">
  <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#a15c45]">Bulk tools</p>
  <h3 className="mt-1 text-base font-semibold text-[#321d1d]">Bulk setup and yearly promotion</h3>
  <p className="mt-1 text-xs leading-5 text-[#786565]">Destination: <strong>{target}</strong> · {studentIds.length} students. Existing destination records are protected and history remains unchanged.</p>
  <fieldset disabled={busy||confirm} className="mt-3 space-y-3">
   <div className="grid gap-3 sm:grid-cols-3"><label className="text-xs">Operation<select className={control} value={mode} onChange={e=>{setMode(e.target.value);setRows(null);}}><option value="SETUP">Set up from current profiles</option><option value="PROMOTE">Promote from previous year</option></select></label>
   {mode==='PROMOTE'&&<label className="text-xs">Source academic year<select className={control} value={sourceYearId} onChange={e=>{setSource(e.target.value);setRows(null);}}><option value="">Select source year</option>{years.filter(year=>year.id!==yearId).map(year=><option key={year.id} value={year.id}>{year.year}</option>)}</select></label>}
   <button type="button" disabled={!studentIds.length||(mode==='PROMOTE'&&!sourceYearId)} className="min-h-11 rounded-lg border border-[#800000] px-4 text-[#800000] disabled:opacity-50" onClick={()=>void preview()}>Preview this page</button></div>
   <p className="rounded-xl border border-amber-200 bg-amber-50 px-3 py-2.5 text-xs leading-5 text-amber-900">Profile values are starting points. Confirm the current year before preparing future years. Year 4 graduation proposals remain unselected until reviewed.</p>
   {rows&&<><div className="divide-y divide-[#ead7d3]">{rows.map(row=><div key={row.studentId} className="py-3"><label className="flex min-h-11 items-center gap-2 font-semibold"><input type="checkbox" disabled={!!row.blocked} checked={row.selected} onChange={e=>change(row.studentId,{selected:e.target.checked})}/>{row.name}</label><p className="text-xs">{row.email} · Source year level: {row.sourceYearLevel??'Not configured'}</p>{row.blocked?<p className="mt-1 text-sm text-[#786565]">Skipped: {row.blocked}</p>:<><div className="mt-2 grid gap-2 sm:grid-cols-3"><label className="text-xs">Program for {row.name}<select className={control} value={row.programId} onChange={e=>change(row.studentId,{programId:e.target.value})}>{programs.map(program=><option key={program.id} value={program.id}>{program.code} – {program.name}</option>)}</select></label><label className="text-xs">Status for {row.name}<select className={control} value={row.status} onChange={e=>change(row.studentId,{status:e.target.value,archiveAccount:e.target.value==='GRADUATED'?row.archiveAccount:false})}>{['ENROLLED','CONTINUING','GRADUATED','WITHDRAWN'].map(status=><option key={status} value={status}>{status}</option>)}</select></label><label className="text-xs">Year level for {row.name}<select className={control} value={row.yearLevel??''} onChange={e=>change(row.studentId,{yearLevel:e.target.value?Number(e.target.value):null})}><option value="">No year level</option>{[1,2,3,4].map(level=><option key={level} value={level}>{level}</option>)}</select></label></div>{row.status==='GRADUATED'&&row.selected&&<label className="mt-3 flex min-h-11 items-center gap-2 rounded-lg border border-[#ead7d3] bg-white px-3 text-sm"><input type="checkbox" checked={row.archiveAccount} onChange={e=>change(row.studentId,{archiveAccount:e.target.checked})}/><span><strong>Archive account after saving graduation</strong><span className="block text-xs text-[#786565]">The student will be signed out and cannot submit requests. Historical records remain available.</span></span></label>}{row.requiresGraduationReview&&<p className="mt-2 text-sm text-amber-800">Review graduation, or change to Year 4 / Continuing for a repeating student.</p>}</>}</div>)}</div>
   <label className="block text-xs">Batch reason / source of confirmation<input maxLength={500} className={control} value={reason} onChange={e=>setReason(e.target.value)}/></label>
   <p className="text-sm">{selected.length} selected · {rows.filter(row=>row.blocked).length} protected or unavailable</p>
   <button type="button" disabled={!selected.length||!reason.trim()||selected.some(row=>!row.programId||(['ENROLLED','CONTINUING'].includes(row.status)&&row.yearLevel===null))} className="min-h-11 rounded-lg bg-[#800000] px-4 text-sm font-semibold text-white disabled:opacity-50" onClick={()=>setConfirm(true)}>Review and save selected</button></>}
  </fieldset>
  {error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}
  <ConfirmationModal isOpen={confirm} title="Save academic batch?" message={`Create ${selected.length} records for ${target}? ${selected.filter(row=>row.status==='GRADUATED').length} selected students will be marked graduated and ${selected.filter(row=>row.archiveAccount).length} accounts will be archived. Existing records and history will be preserved.`} confirmLabel="Save selected records" confirmingLabel="Saving…" cancelLabel="Go back" isConfirming={busy} onConfirm={()=>void save()} onClose={()=>{if(!busy)setConfirm(false);}}/>
 </section>;
}
